apiVersion: v1
kind: Service
metadata:
  name: secpipe-cloudops
  namespace: secpipe-cloudops
spec:
  selector:
    app: secpipe-cloudops
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
